import { Download } from 'lucide-react';
import { learningService } from '../../services/supabase/learningService';
import { useToast } from '../ui/Toast';

const downloadCsv = (name: string, rows: string[][]) => { const text = rows.map(row => row.map(value => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\ufeff${text}`], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };

export default function AcademicExports({ sectionId, sectionCode }: { sectionId: string; sectionCode: string }) {
  const toast = useToast();
  const gradebook = async () => { try { const [students, assessments] = await Promise.all([learningService.getStudents(sectionId), learningService.getAssessments(sectionId)]); const gradeSets = await Promise.all(assessments.map(assessment => learningService.getGrades(assessment.id))); const rows = [['Aluno', 'E-mail', ...assessments.map(item => item.title), 'Total publicado']]; students.forEach(student => { const scores = gradeSets.map(entries => entries.find(entry => entry.student_id === student.student_id)?.score ?? ''); const total = scores.reduce<number>((sum, value) => sum + (typeof value === 'number' ? value : 0), 0); rows.push([student.student?.nome_completo || '', student.student?.email || '', ...scores.map(String), String(total)]); }); downloadCsv(`gradebook-${sectionCode}.csv`, rows); toast.success('Gradebook CSV exportado.'); } catch (error:any) { toast.error(error.message || 'Não foi possível exportar o gradebook.'); } };
  const attendance = async () => { try { const [students, sessions] = await Promise.all([learningService.getStudents(sectionId), learningService.getAttendanceSessions(sectionId)]); const records = await Promise.all(sessions.map(session => learningService.getAttendance(session.id))); const rows = [['Aluno', 'E-mail', ...sessions.map(session => new Date(session.occurred_at).toLocaleDateString('pt-AO')), 'Presenças', 'Ausências']]; students.forEach(student => { const values = records.map(set => set.find(record => record.student_id === student.student_id)?.status || '—'); rows.push([student.student?.nome_completo || '', student.student?.email || '', ...values, String(values.filter(value => value === 'PRESENT' || value === 'LATE').length), String(values.filter(value => value === 'ABSENT').length)]); }); downloadCsv(`frequencia-${sectionCode}.csv`, rows); toast.success('Relatório de frequência CSV exportado.'); } catch (error:any) { toast.error(error.message || 'Não foi possível exportar a frequência.'); } };
  return <div className="flex flex-wrap gap-2"><button disabled={!sectionId} onClick={gradebook} className="inline-flex items-center gap-1.5 rounded-lg border border-[#D6D3D1] px-2.5 py-1.5 text-[10px] font-bold text-[#1C1917] disabled:opacity-50 dark:border-[#273244] dark:text-white"><Download size={13}/>Gradebook CSV</button><button disabled={!sectionId} onClick={attendance} className="inline-flex items-center gap-1.5 rounded-lg border border-[#D6D3D1] px-2.5 py-1.5 text-[10px] font-bold text-[#1C1917] disabled:opacity-50 dark:border-[#273244] dark:text-white"><Download size={13}/>Frequência CSV</button></div>;
}
