import { Award, BarChart3, BookOpen, CalendarDays, ClipboardCheck, MessageSquare, Plus, Settings, Users, X } from 'lucide-react';
import { User } from '../../types';
export type InstructorTab='dashboard'|'cursos'|'criar-curso'|'alunos'|'avaliacoes'|'academico'|'certificados'|'calendario'|'mensagens'|'relatorios'|'perfil'|'configuracoes';
interface Props{activeTab:InstructorTab;open:boolean;user:User|null;onClose:()=>void;onNavigate:(tab:InstructorTab)=>void;onMessages:()=>void;onSignOut:()=>void;}
const groups:Array<{label:string;items:Array<{id:InstructorTab|'messages';label:string;icon:React.ReactNode}>}>=[
 {label:'Visão geral',items:[{id:'dashboard',label:'Dashboard',icon:<BarChart3 size={16}/>}]},
 {label:'Ensino',items:[{id:'cursos',label:'Meus cursos',icon:<BookOpen size={16}/>},{id:'criar-curso',label:'Criar curso',icon:<Plus size={16}/>},{id:'alunos',label:'Meus alunos',icon:<Users size={16}/>},{id:'avaliacoes',label:'Avaliações',icon:<ClipboardCheck size={16}/>},{id:'academico',label:'Turma e avaliação',icon:<BookOpen size={16}/>},{id:'relatorios',label:'Progresso',icon:<BarChart3 size={16}/>}]},
 {label:'Planejamento',items:[{id:'calendario',label:'Agenda letiva',icon:<CalendarDays size={16}/>}]},
 {label:'Comunicação',items:[{id:'messages',label:'Mensagens',icon:<MessageSquare size={16}/>},{id:'certificados',label:'Certificados',icon:<Award size={16}/>}]},
 {label:'Conta',items:[{id:'perfil',label:'Meu perfil',icon:<Users size={16}/>},{id:'configuracoes',label:'Configurações',icon:<Settings size={16}/>}]}
];
export default function InstructorSidebar({activeTab,open,user,onClose,onNavigate,onMessages,onSignOut}:Props){return <>{open&&<button onClick={onClose} aria-label="Fechar navegação docente" className="fixed inset-0 z-40 bg-[#08101C]/60 backdrop-blur-sm lg:hidden"/>}<aside className={`fixed inset-y-0 left-0 z-50 flex w-[240px] flex-col bg-[#0C1828] text-[#ECE9E1] transition-transform duration-200 lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}><div className="flex h-[78px] items-center justify-between border-b border-white/10 px-5"><div className="flex items-center gap-2.5"><img src="/brand/multiplus-academy-logo-original.png" alt="MultiPlus Academy" className="h-8 w-auto"/><div><b className="block font-serif text-sm">MULTIPLUS</b><span className="font-mono text-[8px] font-bold uppercase tracking-[.18em] text-[#E8C77C]">Teaching Studio</span></div></div><button onClick={onClose} className="rounded-lg p-2 text-white/60 hover:bg-white/10 lg:hidden" aria-label="Fechar menu"><X size={18}/></button></div><nav className="min-h-0 flex-1 overflow-y-auto px-3 py-4" aria-label="Navegação do professor">{groups.map(group=><div key={group.label} className="mb-4"><p className="mb-1 px-3 font-mono text-[8px] font-bold uppercase tracking-[.16em] text-white/35">{group.label}</p>{group.items.map(item=>{const active=item.id!=='messages'&&item.id===activeTab;return <button key={item.id} onClick={()=>{if(item.id==='messages')onMessages();else onNavigate(item.id);onClose()}} aria-current={active?'page':undefined} className={`flex min-h-10 w-full items-center gap-3 rounded-lg px-3 text-left text-[13px] transition ${active?'bg-[#C99A47] font-semibold text-[#0C1828]':'text-white/65 hover:bg-white/[.07] hover:text-white'}`}>{item.icon}<span>{item.label}</span></button>})}</div>)}</nav><div className="border-t border-white/10 p-4"><button onClick={()=>{onNavigate('perfil');onClose()}} className="flex w-full items-center gap-3 rounded-lg p-2 text-left hover:bg-white/[.07]"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-[#C99A47]/50 bg-[#16263C] text-xs font-bold text-[#E8C77C]">{user?.firstName?.[0]||'P'}</span><span className="min-w-0 flex-1"><b className="block truncate text-xs text-white">{user?.firstName||'Professor'} {user?.lastName||''}</b><small className="block font-mono text-[9px] text-white/40">Perfil docente</small></span></button><button onClick={onSignOut} className="mt-3 min-h-10 w-full rounded-lg border border-white/10 font-mono text-[10px] font-bold uppercase tracking-wide text-white/60 hover:border-[#C99A47]/50 hover:text-[#E8C77C]">Sair</button></div></aside></>}
