import { useEffect, useRef } from 'react';
import { Bell, CheckCheck, X } from 'lucide-react';
import { supabase } from '../../lib/supabase/client';
import { useToast } from '../ui/Toast';

interface Props { userId?: string; notifications: any[]; onChange: (items: any[]) => void; onClose: () => void; }
export default function InstructorNotificationPopover({ userId, notifications, onChange, onClose }: Props) {
  const toast = useToast(); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const dismiss = (event: PointerEvent) => { if (!ref.current?.contains(event.target as Node)) onClose(); }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('pointerdown', dismiss); document.addEventListener('keydown', escape); return () => { document.removeEventListener('pointerdown', dismiss); document.removeEventListener('keydown', escape); }; }, [onClose]);
  const markAll = async () => { if (!userId) return; try { const { error } = await supabase.from('notifications').update({ read: true }).eq('user_id', userId).eq('read', false); if (error) throw error; onChange(notifications.map(item => ({ ...item, read: true }))); toast.success('Todos os avisos foram marcados como lidos.'); } catch (error: any) { toast.error(error.message || 'Não foi possível atualizar os avisos.'); } };
  return <div ref={ref} role="dialog" aria-label="Avisos docentes" className="fixed inset-x-3 top-[4.75rem] z-[80] max-h-[70dvh] overflow-hidden rounded-2xl border border-[#E4E0D7] bg-white p-4 shadow-2xl dark:border-[#273244] dark:bg-[#101827] sm:absolute sm:right-7 sm:left-auto sm:top-[4.5rem] sm:w-96"><div className="flex items-center justify-between border-b border-[#E7E5E4] pb-3 dark:border-[#273244]"><div><p className="font-mono text-[9px] font-bold uppercase tracking-widest text-[#A16207]">Central docente</p><h2 className="mt-1 font-serif text-base font-black text-[#1C1917] dark:text-white">Avisos</h2></div><div className="flex items-center gap-1"><button type="button" onClick={markAll} className="rounded-lg px-2 py-1.5 text-[10px] font-bold text-[#A16207] hover:bg-[#F5F0E8]"><CheckCheck className="mr-1 inline" size={13}/>Ler tudo</button><button type="button" onClick={onClose} className="rounded-lg p-2 text-[#78716C] hover:bg-[#F5F0E8]" aria-label="Fechar avisos"><X size={15}/></button></div></div><div className="mt-2 max-h-[52dvh] space-y-1 overflow-y-auto">{notifications.length ? notifications.map(notification => <article key={notification.id} className={`flex gap-3 rounded-xl p-3 ${notification.read ? '' : 'bg-[#F5F0E8] dark:bg-[#A16207]/10'}`}><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${notification.read ? 'bg-[#D6D3D1]' : 'bg-[#A16207]'}`}/><div className="min-w-0"><p className="text-xs leading-relaxed text-[#1C1917] dark:text-white">{notification.text}</p><time className="mt-1 block font-mono text-[9px] text-[#78716C]">{notification.created_at ? new Date(notification.created_at).toLocaleString('pt-AO') : 'Agora'}</time></div></article>) : <div className="py-10 text-center"><Bell className="mx-auto text-[#A16207]" size={22}/><p className="mt-3 text-xs text-[#78716C]">Nenhum aviso pendente.</p></div>}</div></div>;
}
