import { Award, BarChart2, BookOpen, Calendar, ClipboardList, MessageSquare, Settings, User as UserIcon, Users, X } from 'lucide-react';
import { User } from '../../types';

export type InstructorTab = 'dashboard' | 'cursos' | 'criar-curso' | 'alunos' | 'avaliacoes' | 'certificados' | 'calendario' | 'mensagens' | 'relatorios' | 'perfil' | 'configuracoes';
interface Props { activeTab: InstructorTab; open: boolean; user: User | null; onClose: () => void; onNavigate: (tab: InstructorTab) => void; onMessages: () => void; onSignOut: () => void; }
const items: Array<{ id: InstructorTab | 'messages'; label: string; icon: React.ReactNode }> = [
  { id: 'dashboard', label: 'Visão geral', icon: <BarChart2 size={17}/> }, { id: 'cursos', label: 'Meus cursos', icon: <BookOpen size={17}/> }, { id: 'criar-curso', label: 'Criar curso', icon: <BookOpen size={17}/> }, { id: 'alunos', label: 'Meus alunos', icon: <Users size={17}/> }, { id: 'avaliacoes', label: 'Avaliações', icon: <ClipboardList size={17}/> }, { id: 'calendario', label: 'Agenda letiva', icon: <Calendar size={17}/> }, { id: 'certificados', label: 'Certificados', icon: <Award size={17}/> }, { id: 'relatorios', label: 'Progresso', icon: <BarChart2 size={17}/> }, { id: 'messages', label: 'Mensagens', icon: <MessageSquare size={17}/> }, { id: 'configuracoes', label: 'Configurações', icon: <Settings size={17}/> },
];
export default function InstructorSidebar({ activeTab, open, user, onClose, onNavigate, onMessages, onSignOut }: Props) { return <>{open && <button onClick={onClose} aria-label="Fechar menu do professor" className="fixed inset-0 z-40 bg-slate-950/55 backdrop-blur-sm lg:hidden"/>}<aside className={`fixed inset-y-0 left-0 z-50 flex w-[280px] flex-col border-r border-white/10 bg-[#101827] text-cream-100 transition-transform duration-300 lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between border-b border-white/10 p-5"><div className="flex items-center gap-3"><img src="https://res.cloudinary.com/deeki0eou/image/upload/v1782520964/multiplus-academy-logotipo-dourado-sem-fundo_ojals8.png" alt="MultiPlus Academy" className="h-9 w-auto"/><div><p className="font-serif text-sm font-black">MultiPlus</p><p className="text-[9px] font-mono font-bold uppercase tracking-[0.18em] text-gold-600">Academic Studio</p></div></div><button onClick={onClose} className="rounded-xl p-2 lg:hidden" aria-label="Fechar menu"><X size={18}/></button></div><nav className="min-h-0 flex-1 space-y-1 overflow-y-auto p-3" aria-label="Navegação docente"><p className="px-3 py-2 text-[9px] font-mono font-bold uppercase tracking-[0.16em] text-white/35">Gestão de turma</p>{items.map((item) => { const selected = item.id !== 'messages' && activeTab === item.id; return <button key={item.id} onClick={() => { if (item.id === 'messages') onMessages(); else onNavigate(item.id); onClose(); }} aria-current={selected ? 'page' : undefined} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-sm ${selected ? 'bg-gold-600 text-ink-900 shadow-lg shadow-gold-600/15' : 'text-white/75 hover:bg-white/10 hover:text-white'}`}>{item.icon}{item.label}</button>; })}</nav><div className="border-t border-white/10 p-4"><button onClick={() => { onNavigate('perfil'); onClose(); }} className="flex w-full items-center gap-3 rounded-xl p-2 text-left hover:bg-white/10"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-gold-600 font-bold text-ink-900">{user?.firstName?.[0] || 'P'}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{user?.firstName || 'Professor'} {user?.lastName || ''}</b><small className="font-mono text-[10px] text-gold-600">PROFESSOR</small></span><UserIcon size={16} className="text-white/40"/></button><button onClick={onSignOut} className="mt-3 min-h-10 w-full rounded-xl border border-rose-500/25 bg-rose-500/10 text-xs font-mono font-bold uppercase text-rose-200 hover:bg-rose-600 hover:text-white">Sair</button></div></aside></> }
