import { FormEvent, useEffect, useState } from 'react';
import { BookOpenCheck, ClipboardCheck, MessageSquareText, UserCheck } from 'lucide-react';
import { learningService, Assessment, AttendanceRecord, AttendanceSession, GradeEntry, LearningOutcome, LearningSection, SectionStudent, SectionSyllabus } from '../../services/supabase/learningService';
import { useToast } from '../ui/Toast';
import RubricBuilder from './RubricBuilder';

const emptySyllabus = (sectionId: string): SectionSyllabus => ({ section_id: sectionId, overview: '', learning_methodology: '', assessment_policy: '', attendance_policy: '', late_work_policy: '', accessibility_statement: '', published_at: null });

export default function InstructorAcademicWorkspace() {
  const toast = useToast();
  const [sections, setSections] = useState<LearningSection[]>([]); const [sectionId, setSectionId] = useState(''); const [students, setStudents] = useState<SectionStudent[]>([]);
  const [tab, setTab] = useState<'grades'|'attendance'|'syllabus'|'forums'>('grades'); const [assessments, setAssessments] = useState<Assessment[]>([]); const [assessmentId, setAssessmentId] = useState(''); const [grades, setGrades] = useState<GradeEntry[]>([]);
  const [attendanceSessions, setAttendanceSessions] = useState<AttendanceSession[]>([]); const [attendanceId, setAttendanceId] = useState(''); const [attendance, setAttendance] = useState<AttendanceRecord[]>([]);
  const [syllabus, setSyllabus] = useState<SectionSyllabus>(emptySyllabus('')); const [outcomes, setOutcomes] = useState<LearningOutcome[]>([]); const [forums, setForums] = useState<any[]>([]);
  const [assessmentTitle, setAssessmentTitle] = useState(''); const [forumTitle, setForumTitle] = useState(''); const [forumDescription, setForumDescription] = useState(''); const [outcomeTitle, setOutcomeTitle] = useState(''); const [busy, setBusy] = useState(false);

  const selected = sections.find(section => section.id === sectionId);
  const loadSection = async (id: string) => { if (!id) return; try { const [nextStudents,nextAssessments,nextSessions,nextSyllabus,nextForums] = await Promise.all([learningService.getStudents(id),learningService.getAssessments(id),learningService.getAttendanceSessions(id),learningService.getSyllabus(id),learningService.getForums(id)]); setStudents(nextStudents); setAssessments(nextAssessments); setAttendanceSessions(nextSessions); setSyllabus(nextSyllabus || emptySyllabus(id)); setForums(nextForums); setAssessmentId(nextAssessments[0]?.id || ''); setAttendanceId(nextSessions[0]?.id || ''); if (selected?.course_id) setOutcomes(await learningService.getOutcomes(selected.course_id)); } catch (error:any) { toast.error(error.message || 'Não foi possível carregar a turma.'); } };
  useEffect(() => { learningService.getSections().then(data => { setSections(data); setSectionId(data[0]?.id || ''); }).catch(() => toast.error('Não foi possível carregar as turmas.')); }, []);
  useEffect(() => { void loadSection(sectionId); }, [sectionId]);
  useEffect(() => { if (assessmentId) learningService.getGrades(assessmentId).then(setGrades).catch(() => setGrades([])); }, [assessmentId]);
  useEffect(() => { if (attendanceId) learningService.getAttendance(attendanceId).then(setAttendance).catch(() => setAttendance([])); }, [attendanceId]);
  const gradeFor = (studentId:string) => grades.find(grade => grade.student_id === studentId);
  const attendanceFor = (studentId:string) => attendance.find(record => record.student_id === studentId);
  const saveGrade = async (studentId:string, score:string, feedback:string, status:GradeEntry['status']) => { if (!assessmentId) return; setBusy(true); try { await learningService.saveGrade({ assessment_id:assessmentId, student_id:studentId, score:score === '' ? null : Number(score), feedback, status }); setGrades(await learningService.getGrades(assessmentId)); toast.success(status === 'PUBLISHED' ? 'Nota publicada para o aluno.' : 'Rascunho de nota guardado.'); } catch (error:any) { toast.error(error.message || 'Não foi possível guardar a nota.'); } finally { setBusy(false); } };
  const createAssessment = async (event:FormEvent) => { event.preventDefault(); if (!sectionId || !assessmentTitle) return; try { const assessment = await learningService.createAssessment({ section_id:sectionId, title:assessmentTitle, points_possible:100 }); setAssessments([assessment,...assessments]); setAssessmentId(assessment.id); setAssessmentTitle(''); toast.success('Avaliação publicada no gradebook.'); } catch (error:any) { toast.error(error.message || 'Não foi possível criar a avaliação.'); } };
  const createSession = async () => { if (!sectionId) return; try { const session = await learningService.createAttendanceSession(sectionId, `Aula de ${new Date().toLocaleDateString('pt-AO')}`); setAttendanceSessions([session,...attendanceSessions]); setAttendanceId(session.id); setAttendance([]); toast.success('Sessão de presença aberta.'); } catch (error:any) { toast.error(error.message || 'Não foi possível abrir a sessão.'); } };
  const savePresence = async (studentId:string, status:AttendanceRecord['status']) => { if (!attendanceId) return; try { await learningService.saveAttendance({attendance_session_id:attendanceId,student_id:studentId,status,note:null}); setAttendance(await learningService.getAttendance(attendanceId)); } catch (error:any) { toast.error(error.message || 'Não foi possível guardar a presença.'); } };
  const saveSyllabus = async (event:FormEvent) => { event.preventDefault(); try { await learningService.saveSyllabus(syllabus); toast.success('Syllabus da turma guardado.'); } catch (error:any) { toast.error(error.message || 'Não foi possível guardar o syllabus.'); } };
  const createOutcome = async (event:FormEvent) => { event.preventDefault(); if (!selected || !outcomeTitle) return; try { await learningService.createOutcome({course_id:selected.course_id,code:`OA-${outcomes.length+1}`,title:outcomeTitle,description:null}); setOutcomeTitle(''); setOutcomes(await learningService.getOutcomes(selected.course_id)); } catch (error:any) { toast.error(error.message || 'Não foi possível criar o objetivo.'); } };
  const createForum = async (event:FormEvent) => { event.preventDefault(); if (!sectionId || !forumTitle) return; try { await learningService.createForum(sectionId,forumTitle,forumDescription); setForumTitle('');setForumDescription('');setForums(await learningService.getForums(sectionId));toast.success('Fórum publicado para a turma.'); } catch (error:any) { toast.error(error.message || 'Não foi possível criar o fórum.'); } };

  return <div className="space-y-5 text-left"><section className="rounded-2xl border border-gray-150 bg-cream-100 p-5 dark:border-ink-800 dark:bg-ink-900"><p className="text-[9px] font-mono font-bold uppercase tracking-widest text-gold-600">Operação acadêmica</p><div className="mt-2 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="font-serif text-xl font-black text-ink-900 dark:text-cream-100">Turma, avaliação e comunidade</h1><p className="mt-1 text-xs text-neutral-400">Gradebook, presença, syllabus e fóruns no mesmo contexto de turma.</p></div><select value={sectionId} onChange={e=>setSectionId(e.target.value)} className="rounded-xl border border-gray-150 bg-white px-3 py-2 text-xs dark:border-ink-800 dark:bg-ink-950"><option value="">Selecionar turma</option>{sections.map(section=><option key={section.id} value={section.id}>{section.code} — {section.name}</option>)}</select></div></section><div className="flex gap-2 overflow-x-auto">{([{id:'grades',label:'Gradebook',icon:<ClipboardCheck size={15}/>},{id:'attendance',label:'Presença',icon:<UserCheck size={15}/>},{id:'syllabus',label:'Syllabus e objetivos',icon:<BookOpenCheck size={15}/>},{id:'forums',label:'Fóruns',icon:<MessageSquareText size={15}/>}] as const).map(item=><button key={item.id} onClick={()=>setTab(item.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs font-semibold ${tab===item.id?'bg-gold-600 text-ink-900':'bg-cream-200 text-neutral-500 dark:bg-ink-800 dark:text-cream-200'}`}>{item.icon}{item.label}</button>)}</div>
  {tab==='grades'&&<section className="rounded-2xl border border-gray-150 bg-cream-100 p-5 dark:border-ink-800 dark:bg-ink-900"><form onSubmit={createAssessment} className="flex flex-wrap gap-2"><input value={assessmentTitle} onChange={e=>setAssessmentTitle(e.target.value)} className="min-w-48 flex-1 rounded-xl border border-gray-150 bg-white px-3 py-2 text-xs dark:border-ink-800 dark:bg-ink-950" placeholder="Nova avaliação"/><button className="rounded-xl bg-ink-900 px-3 py-2 text-xs font-bold text-white dark:bg-gold-600 dark:text-ink-900">Publicar avaliação</button></form><select value={assessmentId} onChange={e=>setAssessmentId(e.target.value)} className="mt-4 rounded-xl border border-gray-150 bg-white px-3 py-2 text-xs dark:border-ink-800 dark:bg-ink-950"><option value="">Selecionar avaliação</option>{assessments.map(assessment=><option key={assessment.id} value={assessment.id}>{assessment.title} · {assessment.points_possible} pts</option>)}</select><div className="mt-4 space-y-2">{students.map(student=>{const grade=gradeFor(student.student_id);return <GradeRow key={student.id} name={student.student?.nome_completo||'Aluno'} grade={grade} disabled={busy} onSave={saveGrade} studentId={student.student_id}/>})}{!students.length&&<p className="text-xs text-neutral-400">Selecione uma turma com alunos ativos.</p>}</div><RubricBuilder sectionId={sectionId}/></section>}
  {tab==='attendance'&&<section className="rounded-2xl border border-gray-150 bg-cream-100 p-5 dark:border-ink-800 dark:bg-ink-900"><div className="flex flex-wrap gap-2"><button onClick={createSession} className="rounded-xl bg-ink-900 px-3 py-2 text-xs font-bold text-white dark:bg-gold-600 dark:text-ink-900">Abrir sessão de hoje</button><select value={attendanceId} onChange={e=>setAttendanceId(e.target.value)} className="rounded-xl border border-gray-150 bg-white px-3 py-2 text-xs dark:border-ink-800 dark:bg-ink-950">{attendanceSessions.map(session=><option key={session.id} value={session.id}>{session.title}</option>)}</select></div><div className="mt-4 space-y-2">{students.map(student=><div key={student.id} className="flex items-center justify-between rounded-xl border border-gray-150 p-3 dark:border-ink-800"><span className="text-xs font-semibold text-ink-900 dark:text-cream-100">{student.student?.nome_completo||'Aluno'}</span><select value={attendanceFor(student.student_id)?.status||'PRESENT'} onChange={e=>savePresence(student.student_id,e.target.value as AttendanceRecord['status'])} className="rounded-lg border border-gray-150 bg-white px-2 py-1.5 text-[10px] dark:border-ink-800 dark:bg-ink-950">{(['PRESENT','LATE','EXCUSED','ABSENT'] as const).map(value=><option key={value} value={value}>{value}</option>)}</select></div>)}</div></section>}
  {tab==='syllabus'&&<section className="grid gap-5 lg:grid-cols-2"><form onSubmit={saveSyllabus} className="rounded-2xl border border-gray-150 bg-cream-100 p-5 dark:border-ink-800 dark:bg-ink-900"><h2 className="font-serif text-lg font-black text-ink-900 dark:text-cream-100">Syllabus da turma</h2>{(['overview','learning_methodology','assessment_policy','attendance_policy','late_work_policy','accessibility_statement'] as const).map(field=><label key={field} className="mt-3 block text-[10px] font-mono font-bold uppercase text-neutral-400">{field.replaceAll('_',' ')}<textarea value={syllabus[field]||''} onChange={e=>setSyllabus({...syllabus,[field]:e.target.value})} className="mt-1 block min-h-16 w-full rounded-xl border border-gray-150 bg-white p-2 text-xs normal-case dark:border-ink-800 dark:bg-ink-950"/></label>)}<button className="mt-4 rounded-xl bg-ink-900 px-3 py-2 text-xs font-bold text-white dark:bg-gold-600 dark:text-ink-900">Guardar syllabus</button></form><div className="rounded-2xl border border-gray-150 bg-cream-100 p-5 dark:border-ink-800 dark:bg-ink-900"><h2 className="font-serif text-lg font-black text-ink-900 dark:text-cream-100">Objetivos de aprendizagem</h2><form onSubmit={createOutcome} className="mt-3 flex gap-2"><input value={outcomeTitle} onChange={e=>setOutcomeTitle(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-gray-150 bg-white px-3 py-2 text-xs dark:border-ink-800 dark:bg-ink-950" placeholder="Novo objetivo"/><button className="rounded-xl bg-gold-600 px-3 py-2 text-xs font-bold text-ink-900">Adicionar</button></form><div className="mt-4 space-y-2">{outcomes.map(outcome=><div key={outcome.id} className="rounded-xl bg-cream-200 p-3 text-xs dark:bg-ink-800"><b className="font-mono text-[10px] text-gold-600">{outcome.code}</b><p className="mt-1 font-semibold text-ink-900 dark:text-cream-100">{outcome.title}</p></div>)}</div></div></section>}
  {tab==='forums'&&<section className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><form onSubmit={createForum} className="rounded-2xl border border-gray-150 bg-cream-100 p-5 dark:border-ink-800 dark:bg-ink-900"><h2 className="font-serif text-lg font-black text-ink-900 dark:text-cream-100">Novo fórum</h2><input required value={forumTitle} onChange={e=>setForumTitle(e.target.value)} className="mt-3 w-full rounded-xl border border-gray-150 bg-white px-3 py-2 text-xs dark:border-ink-800 dark:bg-ink-950" placeholder="Título"/><textarea value={forumDescription} onChange={e=>setForumDescription(e.target.value)} className="mt-3 min-h-24 w-full rounded-xl border border-gray-150 bg-white p-3 text-xs dark:border-ink-800 dark:bg-ink-950" placeholder="Orientação da discussão"/><button className="mt-3 rounded-xl bg-ink-900 px-3 py-2 text-xs font-bold text-white dark:bg-gold-600 dark:text-ink-900">Publicar fórum</button></form><div className="space-y-2">{forums.map(forum=><article key={forum.id} className="rounded-2xl border border-gray-150 bg-cream-100 p-4 dark:border-ink-800 dark:bg-ink-900"><h3 className="text-sm font-semibold text-ink-900 dark:text-cream-100">{forum.title}</h3><p className="mt-1 text-xs text-neutral-400">{forum.description||'Sem orientação adicional.'}</p></article>)}</div></section>}</div>;
}

function GradeRow({name,grade,studentId,onSave,disabled}:{name:string;grade?:GradeEntry;studentId:string;disabled:boolean;onSave:(studentId:string,score:string,feedback:string,status:GradeEntry['status'])=>void}) { const [score,setScore]=useState(grade?.score?.toString()||'');const [feedback,setFeedback]=useState(grade?.feedback||'');useEffect(()=>{setScore(grade?.score?.toString()||'');setFeedback(grade?.feedback||'')},[grade?.id,grade?.score,grade?.feedback]);return <div className="grid gap-2 rounded-xl border border-gray-150 p-3 dark:border-ink-800 sm:grid-cols-[1fr_90px_1.3fr_auto_auto]"><span className="self-center text-xs font-semibold text-ink-900 dark:text-cream-100">{name}</span><input type="number" min="0" value={score} onChange={e=>setScore(e.target.value)} className="rounded-lg border border-gray-150 bg-white px-2 py-1.5 text-xs dark:border-ink-800 dark:bg-ink-950" placeholder="Nota"/><input value={feedback} onChange={e=>setFeedback(e.target.value)} className="rounded-lg border border-gray-150 bg-white px-2 py-1.5 text-xs dark:border-ink-800 dark:bg-ink-950" placeholder="Feedback"/><button disabled={disabled} onClick={()=>onSave(studentId,score,feedback,'GRADED')} className="rounded-lg border border-gray-150 px-2 py-1.5 text-[10px] font-bold">Guardar</button><button disabled={disabled} onClick={()=>onSave(studentId,score,feedback,'PUBLISHED')} className="rounded-lg bg-gold-600 px-2 py-1.5 text-[10px] font-bold text-ink-900">Publicar</button></div> }
