import { FormEvent, useEffect, useState } from 'react';
import { ListChecks, Plus } from 'lucide-react';
import { learningService, RubricCriterion } from '../../services/supabase/learningService';
import { useToast } from '../ui/Toast';

export default function RubricBuilder({ sectionId }: { sectionId: string }) {
  const toast=useToast(); const [rubrics,setRubrics]=useState<Array<{id:string;name:string;description:string|null}>>([]);const [rubricId,setRubricId]=useState('');const [criteria,setCriteria]=useState<RubricCriterion[]>([]);const [name,setName]=useState('');const [criterion,setCriterion]=useState('');const [points,setPoints]=useState('10');
  const load=async()=>{if(!sectionId)return;const data=await learningService.getRubrics(sectionId);setRubrics(data);setRubricId(data[0]?.id||'')}; useEffect(()=>{void load()},[sectionId]); useEffect(()=>{if(rubricId)learningService.getRubricCriteria(rubricId).then(setCriteria).catch(()=>setCriteria([]))},[rubricId]);
  const makeRubric=async(e:FormEvent)=>{e.preventDefault();if(!name)return;try{const data=await learningService.createRubric(sectionId,name,'');setName('');await load();setRubricId(data.id);toast.success('Rubrica criada.')}catch(error:any){toast.error(error.message||'Não foi possível criar a rubrica.')}};
  const addCriterion=async(e:FormEvent)=>{e.preventDefault();if(!rubricId||!criterion)return;try{await learningService.createRubricCriterion({rubric_id:rubricId,description:criterion,points_possible:Number(points),sort_order:criteria.length,levels:[{label:'Insuficiente',points:0},{label:'Adequado',points:Number(points)*0.7},{label:'Excelente',points:Number(points)}]});setCriterion('');setCriteria(await learningService.getRubricCriteria(rubricId));toast.success('Critério incluído na rubrica.')}catch(error:any){toast.error(error.message||'Não foi possível incluir o critério.')}};
  return <section className="mt-5 rounded-2xl border border-gray-150 bg-white p-4 dark:border-ink-800 dark:bg-ink-950"><div className="flex items-center gap-2"><ListChecks size={16} className="text-gold-600"/><h3 className="text-sm font-semibold text-ink-900 dark:text-cream-100">Rubrica por critérios</h3></div><div className="mt-3 grid gap-3 md:grid-cols-2"><form onSubmit={makeRubric} className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-gray-150 px-2 py-1.5 text-xs dark:border-ink-800 dark:bg-ink-900" placeholder="Nome da rubrica"/><button className="rounded-lg bg-gold-600 px-2 text-ink-900"><Plus size={14}/></button></form><select value={rubricId} onChange={e=>setRubricId(e.target.value)} className="rounded-lg border border-gray-150 px-2 py-1.5 text-xs dark:border-ink-800 dark:bg-ink-900"><option value="">Selecionar rubrica</option>{rubrics.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>{rubricId&&<><form onSubmit={addCriterion} className="mt-3 grid gap-2 sm:grid-cols-[1fr_80px_auto]"><input value={criterion} onChange={e=>setCriterion(e.target.value)} className="rounded-lg border border-gray-150 px-2 py-1.5 text-xs dark:border-ink-800 dark:bg-ink-900" placeholder="Critério: domínio técnico"/><input type="number" min="1" value={points} onChange={e=>setPoints(e.target.value)} className="rounded-lg border border-gray-150 px-2 py-1.5 text-xs dark:border-ink-800 dark:bg-ink-900"/><button className="rounded-lg border border-gold-600 px-2 py-1.5 text-[10px] font-bold text-gold-600">Adicionar</button></form><div className="mt-3 space-y-2">{criteria.map(item=><div key={item.id} className="rounded-lg bg-cream-200 p-2.5 text-xs dark:bg-ink-800"><div className="flex justify-between gap-3"><b className="text-ink-900 dark:text-cream-100">{item.description}</b><span className="font-mono text-gold-600">{item.points_possible} pts</span></div><p className="mt-1 text-[10px] text-neutral-500">{item.levels.map(level=>`${level.label}: ${level.points}`).join(' · ')}</p></div>)}</div></>}</section>;
}
