import { Bell, CheckCheck, MessageSquare, Award, BookOpen, ClipboardList } from 'lucide-react';
import { supabase } from '../../lib/supabase/client';
import { useToast } from '../ui/Toast';

interface Props { notifications: any[]; setNotifications: (value: any[] | ((previous: any[]) => any[])) => void; setActiveTab: (tab: any) => void; setCurrentPage: (page: any) => void; }

const getDestination = (notification: any) => {
  if (notification.link) return notification.link.replace(/^\//, '');
  const type = String(notification.type || '').toLowerCase(); const text = String(notification.text || '').toLowerCase();
  if (type.includes('certificate') || text.includes('certificado')) return 'certificates';
  if (type.includes('assignment') || text.includes('tarefa')) return 'tasks';
  if (type.includes('message') || text.includes('mensagem')) return 'messages';
  if (type.includes('lesson') || type.includes('enrollment') || text.includes('aula') || text.includes('matriculado')) return 'courses';
  return 'dashboard';
};
const iconFor = (destination: string) => destination === 'certificates' ? <Award size={18} /> : destination === 'tasks' ? <ClipboardList size={18} /> : destination === 'messages' ? <MessageSquare size={18} /> : <BookOpen size={18} />;

export default function StudentNotificationCenter({ notifications, setNotifications, setActiveTab, setCurrentPage }: Props) {
  const toast = useToast(); const unread = notifications.filter((item) => !item.read).length;
  const markRead = async (notification: any, open = false) => { try { if (!notification.read) { const { error } = await supabase.from('notifications').update({ read: true }).eq('id', notification.id); if (error) throw error; setNotifications((previous) => previous.map((item) => item.id === notification.id ? { ...item, read: true } : item)); } if (open) { const destination = getDestination(notification); if (destination === 'messages') setCurrentPage('messages'); else setActiveTab(destination); } } catch (error: any) { toast.error(error?.message || 'Não foi possível atualizar a notificação.'); } };
  const markAll = async () => { try { const ids = notifications.filter((item) => !item.read).map((item) => item.id); if (ids.length) { const { error } = await supabase.from('notifications').update({ read: true }).in('id', ids); if (error) throw error; setNotifications((previous) => previous.map((item) => ({ ...item, read: true }))); } toast.success('Todas as notificações foram marcadas como lidas.'); } catch (error: any) { toast.error(error?.message || 'Erro ao atualizar notificações.'); } };
  return <div className="mx-auto max-w-4xl space-y-6 text-left"><section className="flex flex-col gap-4 rounded-3xl border border-gray-150 bg-white p-6 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:flex-row sm:items-end sm:justify-between sm:p-8"><div className="flex gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-gold-600/15 text-gold-600"><Bell size={20} /></span><div><p className="text-[10px] font-mono font-bold uppercase tracking-[0.16em] text-gold-600">Central acadêmica</p><h1 className="font-serif text-2xl font-black text-ink-900 dark:text-cream-100">Notificações</h1><p className="mt-1 text-xs text-neutral-400">{unread ? `${unread} aviso(s) ainda não lido(s)` : 'Você está em dia com seus avisos.'}</p></div></div><button onClick={markAll} disabled={!unread} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-gray-250 px-4 text-xs font-mono font-bold uppercase text-ink-900 hover:border-gold-600 disabled:opacity-50 dark:border-ink-800 dark:text-cream-100"><CheckCheck size={16} />Marcar todas lidas</button></section><section className="overflow-hidden rounded-3xl border border-gray-150 bg-white shadow-sm dark:border-ink-800 dark:bg-ink-900">{notifications.length ? <ul className="divide-y divide-gray-100 dark:divide-ink-800">{notifications.map((notification) => { const destination = getDestination(notification); return <li key={notification.id}><button onClick={() => markRead(notification, true)} className={`flex min-h-20 w-full gap-4 p-5 text-left transition hover:bg-gold-600/[0.05] ${notification.read ? '' : 'bg-gold-600/[0.04]'}`}><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${notification.read ? 'bg-cream-200 text-neutral-400 dark:bg-ink-950' : 'bg-gold-600/15 text-gold-600'}`}>{iconFor(destination)}</span><span className="min-w-0 flex-1"><span className="block text-sm text-ink-900 dark:text-cream-100">{notification.text}</span><time className="mt-1 block text-[10px] font-mono text-neutral-400">{notification.created_at ? new Date(notification.created_at).toLocaleString('pt-AO') : 'Agora'}</time></span>{!notification.read && <span className="self-start rounded-lg bg-gold-600 px-2 py-1 text-[9px] font-mono font-bold text-ink-900">NOVA</span>}</button></li>; })}</ul> : <div className="p-12 text-center"><Bell className="mx-auto text-gold-600" size={28}/><h2 className="mt-3 font-serif text-lg font-black text-ink-900 dark:text-cream-100">Sem notificações</h2><p className="mt-1 text-sm text-neutral-400">Novos avisos sobre aulas, tarefas e certificados aparecerão aqui.</p></div>}</section></div>;
}
