import { useEffect, useState } from 'react';
import { Award, BookOpen, CheckCircle2, Clock3, Loader2, TrendingUp } from 'lucide-react';
import { User } from '../../types';
import { academicService } from '../../services/supabase/academicService';

interface StudentProgressTabProps { currentUser: User | null; }

export default function StudentProgressTab({ currentUser }: StudentProgressTabProps) {
  const [metrics, setMetrics] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!currentUser?.id) { setLoading(false); return; } academicService.getStudentProgressMetrics(currentUser.id).then(setMetrics).catch((error) => console.error('Progress metrics:', error)).finally(() => setLoading(false)); }, [currentUser?.id]);
  const totals = metrics.reduce((acc, row) => ({ total: acc.total + Number(row.total_lessons || 0), complete: acc.complete + Number(row.completed_lessons || 0) }), { total: 0, complete: 0 });
  const progress = totals.total ? Math.round((totals.complete / totals.total) * 100) : 0;
  if (loading) return <div className="flex min-h-56 flex-col items-center justify-center gap-3 rounded-3xl border border-gray-150 bg-white dark:border-ink-800 dark:bg-ink-900"><Loader2 className="animate-spin text-gold-600" /><p className="text-xs text-neutral-400">A carregar progresso real…</p></div>;
  return <div className="space-y-6 text-left"><section className="rounded-3xl border border-gray-150 bg-white p-6 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:p-8"><p className="text-[10px] font-mono font-bold uppercase tracking-[0.16em] text-gold-600">Desempenho acadêmico</p><h1 className="mt-1 font-serif text-xl font-black sm:text-2xl text-ink-900 dark:text-cream-100">Meu progresso</h1><p className="mt-1 text-xs text-neutral-400">Dados calculados por curso, aulas concluídas e avaliações registradas.</p></section><section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-gray-150 bg-white p-5 dark:border-ink-800 dark:bg-ink-900"><TrendingUp className="text-emerald-600" size={19}/><p className="mt-4 text-[10px] font-mono uppercase text-neutral-400">Progresso global</p><p className="mt-1 font-serif text-xl font-black sm:text-2xl text-ink-900 dark:text-cream-100">{progress}%</p></article><article className="rounded-2xl border border-gray-150 bg-white p-5 dark:border-ink-800 dark:bg-ink-900"><CheckCircle2 className="text-gold-600" size={19}/><p className="mt-4 text-[10px] font-mono uppercase text-neutral-400">Aulas concluídas</p><p className="mt-1 font-serif text-xl font-black sm:text-2xl text-ink-900 dark:text-cream-100">{totals.complete}/{totals.total}</p></article><article className="rounded-2xl border border-gray-150 bg-white p-5 dark:border-ink-800 dark:bg-ink-900"><Clock3 className="text-blue-600" size={19}/><p className="mt-4 text-[10px] font-mono uppercase text-neutral-400">Tempo estudado</p><p className="mt-1 font-serif text-xl font-black sm:text-2xl text-ink-900 dark:text-cream-100">{currentUser?.totalHoursLearned || 0} h</p></article></section><section className="overflow-hidden rounded-3xl border border-gray-150 bg-white shadow-sm dark:border-ink-800 dark:bg-ink-900"><div className="border-b border-gray-100 p-5 dark:border-ink-800"><h2 className="font-serif text-lg font-black text-ink-900 dark:text-cream-100">Por curso</h2></div><ul className="divide-y divide-gray-100 dark:divide-ink-800">{metrics.map((row) => <li key={row.course_id} className="grid gap-3 p-5 sm:grid-cols-[1fr_auto_auto]"><div><h3 className="text-sm font-bold text-ink-900 dark:text-cream-100">{row.course_title || 'Curso'}</h3><p className="mt-1 text-xs text-neutral-400">{row.completed_lessons || 0} de {row.total_lessons || 0} aulas concluídas</p></div><span className="self-center text-xs font-mono text-neutral-400">Quiz: {row.avg_quiz_score ? `${Math.round(row.avg_quiz_score)}%` : 'sem notas'}</span><span className="self-center rounded-lg bg-gold-600/15 px-2 py-1 text-xs font-mono font-bold text-gold-700 dark:text-gold-500">{row.progress_percent || 0}%</span></li>)}{metrics.length === 0 && <li className="p-10 text-center text-sm text-neutral-400"><BookOpen className="mx-auto text-gold-600" /><p className="mt-3">O progresso aparecerá quando houver cursos e aulas registradas.</p></li>}</ul></section></div>;
}
