import { CalendarClock, Download, History, Lock, PlayCircle } from 'lucide-react';
import { getLessonAvailability } from '../../lib/academic/lessonAccess';

interface StudentCalendarPageProps { timeline: any[]; onExport: () => void; }

export default function StudentCalendarPage({ timeline, onExport }: StudentCalendarPageProps) {
  const groups = { UPCOMING: [] as any[], ACTIVE: [] as any[], ENDED: [] as any[], UNSCHEDULED: [] as any[] };
  timeline.forEach((item) => { const availability = getLessonAvailability(item.lesson); groups[availability].push(item.lesson); });
  const section = (title: string, description: string, lessons: any[], icon: React.ReactNode, empty: string, color: string) => <section className="rounded-3xl border border-gray-150 bg-white p-5 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:p-6"><div className="flex gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${color}`}>{icon}</span><div><h2 className="font-serif text-lg font-black text-ink-900 dark:text-cream-100">{title}</h2><p className="mt-1 text-xs text-neutral-400">{description}</p></div></div><div className="mt-5 space-y-3">{lessons.map((lesson) => { const start = lesson.access_starts_at || lesson.scheduled_at; return <article key={lesson.id} className="rounded-2xl border border-gray-150 p-4 dark:border-ink-800"><p className="text-[10px] font-mono font-bold uppercase tracking-wider text-gold-600">{lesson.course?.title || 'Curso'}</p><h3 className="mt-1 text-sm font-bold text-ink-900 dark:text-cream-100">{lesson.titulo || lesson.title}</h3><p className="mt-2 text-xs text-neutral-400">{start ? new Date(start).toLocaleString('pt-AO', { dateStyle: 'medium', timeStyle: 'short' }) : 'Horário não definido'}{lesson.access_ends_at ? ` — encerra às ${new Date(lesson.access_ends_at).toLocaleTimeString('pt-AO', { hour: '2-digit', minute: '2-digit' })}` : ''}</p></article>; })}{!lessons.length && <p className="rounded-xl bg-cream-200 p-4 text-xs text-neutral-400 dark:bg-ink-950">{empty}</p>}</div></section>;
  return <div className="space-y-6 text-left"><section className="flex flex-col gap-4 rounded-3xl border border-gray-150 bg-white p-6 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:flex-row sm:items-end sm:justify-between sm:p-8"><div><p className="text-[10px] font-mono font-bold uppercase tracking-[0.16em] text-gold-600">Linha do tempo acadêmica</p><h1 className="mt-1 font-serif text-2xl font-black text-ink-900 dark:text-cream-100">Calendário letivo</h1><p className="mt-1 text-xs text-neutral-400">Acompanhe aulas futuras, disponíveis e registradas no histórico.</p></div><button onClick={onExport} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-gray-250 px-4 text-xs font-mono font-bold uppercase text-ink-900 hover:border-gold-600 dark:border-ink-800 dark:text-cream-100"><Download size={16} />Exportar calendário</button></section><div className="grid gap-5 xl:grid-cols-3">{section('Próximas aulas', 'O acesso abre automaticamente no horário informado.', groups.UPCOMING, <Lock size={19} />, 'Não há aulas futuras agendadas.', 'bg-amber-50 text-amber-700 dark:bg-amber-950/20 dark:text-amber-300')}{section('Disponíveis agora', 'Aulas abertas na janela de acesso atual.', groups.ACTIVE, <PlayCircle size={19} />, 'Nenhuma aula está aberta agora.', 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/20 dark:text-emerald-300')}{section('Histórico', 'Aulas encerradas preservadas como registro letivo.', groups.ENDED, <History size={19} />, 'Nenhuma aula encerrada ainda.', 'bg-slate-100 text-slate-700 dark:bg-ink-950 dark:text-cream-100')}</div><div className="rounded-2xl border border-blue-100 bg-blue-50/60 p-4 text-xs leading-relaxed text-blue-800 dark:border-blue-900/30 dark:bg-blue-950/20 dark:text-blue-300"><CalendarClock className="mr-2 inline" size={16} />O arquivo ICS usa início e fim reais da aula quando ambos estão definidos.</div></div>;
}
