import { useState } from 'react';
import { Award, Plus, ShieldCheck } from 'lucide-react';
import CertificateIssueModal from '../certificates/CertificateIssueModal';

interface AdminCertificatesPageProps { certificates: any[]; onRefresh: () => Promise<void> | void; }
export default function AdminCertificatesPage({ certificates, onRefresh }: AdminCertificatesPageProps) {
  const [issue, setIssue] = useState(false);
  return <div className="space-y-6 text-left"><section className="flex flex-col gap-4 rounded-3xl border border-gray-150 bg-white p-6 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:flex-row sm:items-end sm:justify-between sm:p-8"><div><p className="text-[10px] font-mono font-bold uppercase tracking-[0.16em] text-gold-600">Credenciais acadêmicas</p><h2 className="mt-1 font-serif text-2xl font-black text-ink-900 dark:text-cream-100">Certificados PDF</h2><p className="mt-1 text-xs text-neutral-400">Arquivos privados, emissão auditada e validação por código.</p></div><button onClick={() => setIssue(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-ink-900 px-4 text-xs font-mono font-bold uppercase text-white hover:bg-gold-600 hover:text-ink-900 dark:bg-gold-600 dark:text-ink-900"><Plus size={16} />Emitir certificado</button></section><section className="overflow-hidden rounded-3xl border border-gray-150 bg-white shadow-sm dark:border-ink-800 dark:bg-ink-900"><ul className="divide-y divide-gray-100 dark:divide-ink-800">{certificates.map((certificate) => <li key={certificate.verificationCode || certificate.certificateNumber} className="flex gap-4 p-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gold-600/15 text-gold-600"><Award size={19} /></span><div className="min-w-0 flex-1"><h3 className="text-sm font-bold text-ink-900 dark:text-cream-100">{certificate.recipientName || 'Aluno'}</h3><p className="mt-1 text-xs text-neutral-400">{certificate.courseName || 'Curso MultiPlus'}</p><p className="mt-1 text-[10px] font-mono text-neutral-400">{certificate.verificationCode || certificate.certificateNumber}</p></div><span className="inline-flex h-fit items-center gap-1 rounded-lg bg-emerald-50 px-2 py-1 text-[9px] font-mono font-bold text-emerald-700"><ShieldCheck size={12} />VÁLIDO</span></li>)}{certificates.length === 0 && <li className="p-12 text-center text-sm text-neutral-400">Nenhum certificado emitido.</li>}</ul></section>{issue && <CertificateIssueModal onClose={() => setIssue(false)} onSave={async () => { setIssue(false); await onRefresh(); }} />}</div>;
}
