import { useEffect, useState } from 'react';
import { ClipboardList, Loader2 } from 'lucide-react';
import { supabase } from '../../lib/supabase/client';

export default function AdminAuditLogPage() {
  const [logs, setLogs] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { supabase.from('audit_logs').select('id, action, entity_type, metadata, created_at, actor:users(nome_completo, email)').order('created_at', { ascending: false }).limit(100).then(({ data, error }) => { if (!error) setLogs(data || []); setLoading(false); }); }, []);
  return <div className="space-y-6 text-left"><section className="rounded-3xl border border-gray-150 bg-white p-6 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:p-8"><div className="flex gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-gold-600/15 text-gold-600"><ClipboardList size={20} /></span><div><p className="text-[10px] font-mono font-bold uppercase tracking-[0.16em] text-gold-600">Rastreabilidade</p><h2 className="font-serif text-2xl font-black text-ink-900 dark:text-cream-100">Auditoria administrativa</h2><p className="mt-1 text-xs text-neutral-400">Últimas 100 operações registradas por serviços autorizados.</p></div></div></section><section className="overflow-hidden rounded-3xl border border-gray-150 bg-white shadow-sm dark:border-ink-800 dark:bg-ink-900">{loading ? <div className="flex min-h-48 items-center justify-center gap-2 text-sm text-neutral-400"><Loader2 className="animate-spin text-gold-600" size={20} />A carregar auditoria…</div> : <ul className="divide-y divide-gray-100 dark:divide-ink-800">{logs.map((log) => <li key={log.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto]"><div><p className="text-xs font-mono font-bold text-gold-600">{log.action}</p><p className="mt-1 text-sm text-ink-900 dark:text-cream-100">{log.entity_type}</p><p className="mt-1 text-[10px] text-neutral-400">{log.actor?.nome_completo || log.actor?.email || 'Sistema'}</p></div><time className="text-[10px] font-mono text-neutral-400">{new Date(log.created_at).toLocaleString('pt-AO')}</time></li>)}{logs.length === 0 && <li className="p-12 text-center text-sm text-neutral-400">Ainda não há eventos de auditoria.</li>}</ul>}</section></div>;
}
