import { Activity, Bell, BookOpen, ChevronRight, FileCheck2, MessageSquare, Network, Settings, Users, X } from 'lucide-react';
import { User } from '../../types';

export type AdminTab = 'dashboard' | 'utilizadores' | 'cursos' | 'certificados' | 'notificacoes' | 'auditoria' | 'integracoes' | 'configuracoes' | 'perfil';
interface Props { activeTab: AdminTab; isOpen: boolean; user: User | null; onClose: () => void; onNavigate: (tab: AdminTab) => void; onMessages: () => void; onSignOut: () => void; }
const items: Array<{ id: AdminTab | 'messages'; label: string; icon: React.ReactNode }> = [
  { id:'dashboard', label:'Visão geral', icon:<Activity size={17}/> }, { id:'utilizadores', label:'Pessoas', icon:<Users size={17}/> }, { id:'cursos', label:'Cursos', icon:<BookOpen size={17}/> }, { id:'certificados', label:'Certificados', icon:<FileCheck2 size={17}/> }, { id:'messages', label:'Mensagens', icon:<MessageSquare size={17}/> }, { id:'notificacoes', label:'Avisos', icon:<Bell size={17}/> }, { id:'auditoria', label:'Histórico', icon:<Activity size={17}/> }, { id:'integracoes', label:'Integrações', icon:<Network size={17}/> }, { id:'configuracoes', label:'Configurações', icon:<Settings size={17}/> },
];
export default function AdminSidebar({activeTab,isOpen,user,onClose,onNavigate,onMessages,onSignOut}:Props){return <>{isOpen&&<button onClick={onClose} aria-label="Fechar navegação" className="fixed inset-0 z-40 bg-[#08101C]/60 backdrop-blur-sm lg:hidden"/>}<aside className={`fixed inset-y-0 left-0 z-50 flex w-[232px] flex-col bg-[#081525] text-[#EDEAE2] transition-transform duration-200 lg:translate-x-0 ${isOpen?'translate-x-0':'-translate-x-full'}`}><div className="flex h-[78px] items-center justify-between border-b border-white/10 px-5"><div className="flex items-center gap-3"><img src="https://res.cloudinary.com/deeki0eou/image/upload/v1782520964/multiplus-academy-logotipo-dourado-sem-fundo_ojals8.png" alt="MultiPlus Academy" className="h-8 w-auto"/><span className="font-serif text-sm font-black tracking-wide">MULTIPLUS</span></div><button onClick={onClose} className="rounded-lg p-2 text-white/60 hover:bg-white/10 lg:hidden" aria-label="Fechar menu"><X size={18}/></button></div><nav className="min-h-0 flex-1 space-y-1 overflow-y-auto px-3 py-6" aria-label="Navegação administrativa"><p className="mb-3 px-3 font-mono text-[9px] font-bold uppercase tracking-[.18em] text-[#C99A47]">Administração</p>{items.map(item=>{const active=item.id!=='messages'&&activeTab===item.id;return <button key={item.id} onClick={()=>{if(item.id==='messages')onMessages();else onNavigate(item.id);onClose()}} aria-current={active?'page':undefined} className={`group flex min-h-10 w-full items-center gap-3 rounded-lg px-3 text-left text-[13px] transition-colors ${active?'bg-[#C99A47] text-[#081525]':'text-white/65 hover:bg-white/[.07] hover:text-white'}`}>{item.icon}<span className="flex-1">{item.label}</span>{active&&<ChevronRight size={14}/>}</button>})}</nav><div className="border-t border-white/10 p-3"><button onClick={()=>{onNavigate('perfil');onClose()}} className="flex w-full items-center gap-3 rounded-lg p-2 text-left hover:bg-white/[.07]"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-[#C99A47]/50 bg-[#132439] text-xs font-bold text-[#E8C77C]">{user?.firstName?.[0]||'A'}</span><span className="min-w-0 flex-1"><b className="block truncate text-xs text-white">{user?.firstName||'Administrador'} {user?.lastName||''}</b><small className="block font-mono text-[9px] text-white/45">Perfil e preferências</small></span></button><button onClick={onSignOut} className="mt-3 min-h-10 w-full rounded-lg border border-white/10 text-[10px] font-mono font-bold uppercase tracking-wide text-white/60 transition hover:border-[#C99A47]/50 hover:text-[#E8C77C]">Sair</button></div></aside></>}
