import { useState } from 'react';
import { BookOpen, Pencil, Users } from 'lucide-react';
import { Course } from '../../types';
import CourseEditorModal from '../course/CourseEditorModal';

interface AdminCoursesPageProps { courses: Course[]; onRefresh: () => Promise<void> | void; }
export default function AdminCoursesPage({ courses, onRefresh }: AdminCoursesPageProps) {
  const [editing, setEditing] = useState<Course | null>(null);
  return <div className="space-y-6 text-left"><section className="rounded-3xl border border-gray-150 bg-white p-6 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:p-8"><p className="text-[10px] font-mono font-bold uppercase tracking-[0.16em] text-gold-600">Catálogo acadêmico</p><h2 className="mt-1 font-serif text-2xl font-black text-ink-900 dark:text-cream-100">Cursos e turmas</h2><p className="mt-1 text-xs text-neutral-400">Acompanhe publicação, professor responsável e gestão de conteúdo.</p></section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courses.map((course) => <article key={course.id} className="flex min-h-56 flex-col rounded-3xl border border-gray-150 bg-white p-5 shadow-sm dark:border-ink-800 dark:bg-ink-900"><div className="flex items-start justify-between gap-3"><span className={`rounded-lg px-2 py-1 text-[9px] font-mono font-bold ${course.status === 'PUBLISHED' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{course.status || 'DRAFT'}</span><button onClick={() => setEditing(course)} className="rounded-xl border border-gray-250 p-2 text-ink-900 hover:border-gold-600 dark:border-ink-800 dark:text-cream-100" aria-label={`Editar ${course.title}`}><Pencil size={15} /></button></div><h3 className="mt-5 font-serif text-lg font-black text-ink-900 dark:text-cream-100">{course.title}</h3><p className="mt-2 line-clamp-3 text-xs leading-relaxed text-neutral-400">{course.summary || course.subtitle || 'Sem descrição.'}</p><div className="mt-auto flex items-center gap-2 border-t border-gray-100 pt-4 text-[10px] font-mono text-neutral-400 dark:border-ink-800"><BookOpen size={13} />{course.duration || 'Duração não definida'}<span className="ml-auto inline-flex items-center gap-1"><Users size={13} />Gerir turma</span></div></article>)}{courses.length === 0 && <div className="rounded-3xl border border-dashed border-gray-250 p-10 text-center text-sm text-neutral-400 md:col-span-2 xl:col-span-3">Nenhum curso encontrado.</div>}</div>{editing && <CourseEditorModal courseId={editing.id} teacherId={editing.teacher_id} onClose={() => setEditing(null)} onSave={async () => { setEditing(null); await onRefresh(); }} />}</div>;
}
