import { useMemo, useState } from 'react';
import { Plus, Search, ShieldAlert, UserCheck, Users } from 'lucide-react';
import { User, UserRole } from '../../types';
import { supabase } from '../../lib/supabase/client';
import { useToast } from '../ui/Toast';
import ConfirmDialog from './ConfirmDialog';

interface AdminUsersPageProps { users: User[]; onRefresh: () => Promise<void> | void; }

export default function AdminUsersPage({ users, onRefresh }: AdminUsersPageProps) {
  const toast = useToast();
  const [query, setQuery] = useState('');
  const [role, setRole] = useState<'ALL' | UserRole>('ALL');
  const [showCreate, setShowCreate] = useState(false);
  const [pending, setPending] = useState<User | null>(null);
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'ALUNO' as UserRole });
  const rows = useMemo(() => users.filter((user) => (role === 'ALL' || user.role === role) && `${user.firstName} ${user.lastName} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [users, role, query]);

  const create = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true);
    try {
      const { data, error } = await supabase.functions.invoke('admin-users', { body: { action: 'create', email: form.email.trim(), password: form.password, nome_completo: form.name.trim(), role: form.role } });
      if (error || data?.error) throw new Error(error?.message || data?.error || 'Não foi possível criar utilizador.');
      toast.success('Utilizador criado com sucesso.'); setShowCreate(false); setForm({ name: '', email: '', password: '', role: 'ALUNO' }); await onRefresh();
    } catch (error: any) { toast.error(error?.message || 'Erro ao criar utilizador.'); } finally { setBusy(false); }
  };
  const toggleStatus = async () => {
    if (!pending) return; setBusy(true);
    try {
      const nextStatus = pending.status === 'ACTIVE' ? 'SUSPENDED' : 'ACTIVE';
      const { data, error } = await supabase.functions.invoke('admin-users', { body: { action: 'update-status', id: pending.id, status: nextStatus } });
      if (error || data?.error) throw new Error(error?.message || data?.error || 'Não foi possível alterar o estado.');
      toast.success(nextStatus === 'ACTIVE' ? 'Conta reativada.' : 'Conta suspensa.'); setPending(null); await onRefresh();
    } catch (error: any) { toast.error(error?.message || 'Erro ao atualizar conta.'); } finally { setBusy(false); }
  };

  return <div className="space-y-6 text-left"><section className="rounded-3xl border border-gray-150 bg-white p-6 shadow-sm dark:border-ink-800 dark:bg-ink-900 sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-mono font-bold uppercase tracking-[0.16em] text-gold-600">Identidade e acesso</p><h2 className="mt-1 font-serif text-2xl font-black text-ink-900 dark:text-cream-100">Utilizadores</h2><p className="mt-1 text-xs text-neutral-400">Gerencie contas, papéis e estados de acesso.</p></div><button onClick={() => setShowCreate(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-ink-900 px-4 text-xs font-mono font-bold uppercase text-white hover:bg-gold-600 hover:text-ink-900 dark:bg-gold-600 dark:text-ink-900"><Plus size={16} />Novo utilizador</button></div><div className="mt-6 grid gap-3 md:grid-cols-[1fr_180px]"><label className="relative"><span className="sr-only">Pesquisar utilizadores</span><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400" size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pesquisar por nome ou e-mail" className="min-h-11 w-full rounded-xl border border-gray-250 bg-cream-200 pl-10 pr-3 text-sm outline-none focus:border-gold-600 dark:border-ink-800 dark:bg-ink-950 dark:text-cream-100" /></label><select value={role} onChange={(event) => setRole(event.target.value as any)} className="min-h-11 rounded-xl border border-gray-250 bg-cream-200 px-3 text-sm outline-none focus:border-gold-600 dark:border-ink-800 dark:bg-ink-950 dark:text-cream-100"><option value="ALL">Todos os papéis</option><option value="ALUNO">Alunos</option><option value="PROFESSOR">Professores</option><option value="ADMIN">Administradores</option></select></div></section>
    <section className="overflow-hidden rounded-3xl border border-gray-150 bg-white shadow-sm dark:border-ink-800 dark:bg-ink-900"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left"><thead className="bg-cream-200 text-[10px] font-mono uppercase tracking-wider text-neutral-400 dark:bg-ink-950"><tr><th className="px-5 py-4">Utilizador</th><th className="px-5 py-4">Papel</th><th className="px-5 py-4">Estado</th><th className="px-5 py-4 text-right">Ação</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-ink-800">{rows.map((user) => <tr key={user.id}><td className="px-5 py-4"><div className="flex items-center gap-3">{user.avatarUrl ? <img src={user.avatarUrl} alt="" className="h-9 w-9 rounded-xl object-cover" /> : <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gold-600/15 font-bold text-gold-600">{user.firstName[0]}</span>}<span><b className="block text-sm text-ink-900 dark:text-cream-100">{user.firstName} {user.lastName}</b><small className="text-neutral-400">{user.email}</small></span></div></td><td className="px-5 py-4 text-xs">{user.role}</td><td className="px-5 py-4"><span className={`rounded-lg px-2 py-1 text-[10px] font-mono font-bold ${user.status === 'ACTIVE' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{user.status}</span></td><td className="px-5 py-4 text-right"><button onClick={() => setPending(user)} className="min-h-9 rounded-lg border border-gray-250 px-3 text-[10px] font-mono font-bold uppercase text-ink-900 hover:border-gold-600 dark:border-ink-800 dark:text-cream-100">{user.status === 'ACTIVE' ? 'Suspender' : 'Reativar'}</button></td></tr>)}</tbody></table></div><div className="space-y-3 p-4 md:hidden">{rows.map((user) => <article key={user.id} className="rounded-2xl border border-gray-150 p-4 dark:border-ink-800"><div className="flex justify-between gap-3"><div><b className="text-sm text-ink-900 dark:text-cream-100">{user.firstName} {user.lastName}</b><p className="mt-1 text-xs text-neutral-400">{user.email}</p></div><span className="text-[10px] font-mono text-gold-600">{user.role}</span></div><button onClick={() => setPending(user)} className="mt-4 min-h-10 w-full rounded-xl border border-gray-250 text-xs font-mono font-bold uppercase dark:border-ink-800">{user.status === 'ACTIVE' ? 'Suspender acesso' : 'Reativar acesso'}</button></article>)}</div>{rows.length === 0 && <div className="flex min-h-48 flex-col items-center justify-center p-6 text-center"><Users className="text-gold-600" /><p className="mt-3 text-sm text-neutral-400">Nenhum utilizador encontrado.</p></div>}</section>
    {showCreate && <dialog open className="w-[min(520px,calc(100vw-2rem))] rounded-3xl border border-gray-150 bg-white p-0 shadow-2xl dark:border-ink-800 dark:bg-ink-900"><form onSubmit={create} className="p-6"><h2 className="font-serif text-xl font-black text-ink-900 dark:text-cream-100">Novo utilizador</h2><div className="mt-5 grid gap-4"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Nome completo" className="min-h-11 rounded-xl border border-gray-250 bg-cream-200 px-3 dark:border-ink-800 dark:bg-ink-950" /><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="E-mail" className="min-h-11 rounded-xl border border-gray-250 bg-cream-200 px-3 dark:border-ink-800 dark:bg-ink-950" /><input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Senha temporária" className="min-h-11 rounded-xl border border-gray-250 bg-cream-200 px-3 dark:border-ink-800 dark:bg-ink-950" /><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as UserRole })} className="min-h-11 rounded-xl border border-gray-250 bg-cream-200 px-3 dark:border-ink-800 dark:bg-ink-950"><option value="ALUNO">Aluno</option><option value="PROFESSOR">Professor</option><option value="ADMIN">Administrador</option></select></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="min-h-11 rounded-xl border border-gray-250 px-4 text-xs font-mono font-bold uppercase">Cancelar</button><button disabled={busy} className="min-h-11 rounded-xl bg-ink-900 px-4 text-xs font-mono font-bold uppercase text-white dark:bg-gold-600 dark:text-ink-900">Criar conta</button></div></form></dialog>}
    <ConfirmDialog open={Boolean(pending)} title={pending?.status === 'ACTIVE' ? 'Suspender acesso?' : 'Reativar acesso?'} description={pending ? `Esta ação altera o acesso de ${pending.firstName} ${pending.lastName}.` : ''} confirmLabel={pending?.status === 'ACTIVE' ? 'Suspender conta' : 'Reativar conta'} danger={pending?.status === 'ACTIVE'} busy={busy} onCancel={() => setPending(null)} onConfirm={toggleStatus} />
  </div>;
}
